import ImageBox from 'src/components/box/ImageBox';
import edwardImg from 'public/images/elliptic-curve/edwards-curve.png';
import { AppArticle } from 'src/components/box/ArticleBox';

export default function Eddsa() {
  return (
    <div className="mt-[1rem]">
      <p className="text-[20px] font-[500]">2. Edwards-curve Digital Signature Algorithm</p>
      <ImageBox src={edwardImg} alt="ecc" title="Edwards curve shape" />
      <AppArticle isFirst>
        The Edwards-curve Digital Signature Algorithm (EdDSA) is a variant of the Schnorr signature
        scheme that utilizes elliptic curves in Edwards form. EdDSA has several advantages,
        including faster computations, better resistance to side-channel attacks, and smaller
        signature sizes. Elliptic curves in Edwards form are defined by the equation:
      </AppArticle>
      <AppArticle isMath className="text-center">
        {'$E_d: x^2 + y^2 = 1 + dx^2y^2, \\text{where d} \\in \\mathbb{K} \\setminus (0, 1)$'}
      </AppArticle>
      <AppArticle isMath>
        {'For two points $(x_1, y_1), (x_2, y_2)$, on the curve, their sum is given by:'}
      </AppArticle>
      <AppArticle isMath className="text-center">
        {
          '$(x_1, y_1) + (x_2, y_2) = (\\frac{x_1y_2 + y_1x_2}{1 + dx_1y_1x_2y_2}, \\frac{y_2y_1 - x_2x_1}{1 - dx_1y_1x_2y_2})$'
        }
      </AppArticle>
      <AppArticle>
        According to this equation, the neutral element is (0, 1), and the negative of a point (x,
        y) is (-x, y).
      </AppArticle>
      <AppArticle isMath>
        {
          'Furthermore, if d is not a square in $\\mathbb{K}$, then the sum of any two points is always well-defined. A generalized form, known as the twisted Edwards curve, is given by:'
        }
      </AppArticle>
      <AppArticle isMath className="text-center">
        {
          '$E_{a,d}: ax^2 + y^2 = 1 + dx^2y^2$, $\\text{where a, d} \\in \\mathbb{K} \\text{\\space are not zero and distinct}.$'
        }
      </AppArticle>
      <AppArticle isMath>
        {
          'The addition law still follows the above equation and has the same neutral element and negation rule.'
        }
      </AppArticle>
      <AppArticle>
        The Edwards-curve Digital Signature Algorithm (EdDSA) is a Schnorr signature scheme using
        Edwards curves. Implementations such as Ed25519, Ed448, and BabyJubJub provide efficient and
        secure digital signatures with compact key sizes.
      </AppArticle>
      <AppArticle isMath>
        {
          'EdDSA uses small $\\textsf{sk}$ and $\\textsf{pk}$ (Ed25519 and Ed448 are 32 and 57 bytes, respectively) and small signatures (Ed25519 and Ed448 are 64 and 114 bytes, respectively). The EdDSA key pair containing $\\textsf{sk}$ is generated by a random integer and the $\\textsf{pk} = \\textsf{sk} * G$.'
        }
      </AppArticle>
    </div>
  );
}
